version: '3.1'

services:
  server-redis:
    image: redis
    container_name: server-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-password}
    networks:
      - server-net

  server-api:
    image: server/api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server-api
    restart: unless-stopped
    ports:
      - "8080:3000"
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD:-password}@server-redis:6379/0
    env_file:
      - ./config/.env
    depends_on:
      - server-redis
    networks:
      - server-net

networks:
  server-net:
    name: server-net
    driver: bridge